version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.34.0
  - dependency-name: sass
    versions:
    - 1.32.10
  - dependency-name: css-loader
    versions:
    - 5.2.2
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: mathjs
    versions:
    - 9.1.0
    - 9.2.0
    - 9.3.1
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: highlight.js
    versions:
    - 10.6.0
    - 10.7.1
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
